# Generated by Django 4.0.3 on 2022-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camera', '0003_tlproject_frames_shot_tlproject_project_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlproject',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='tlproject',
            name='project_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tlproject',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
